<?php
/**
 * SearchApi
 * PHP version 5
 *
 * @category Class
 * @package  WsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Fitment API
 *
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace WsApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use WsApiClient\ApiException;
use WsApiClient\Configuration;
use WsApiClient\HeaderSelector;
use WsApiClient\ObjectSerializer;

/**
 * SearchApi Class Doc Comment
 *
 * @category Class
 * @package  WsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation searchByHfTireList
     *
     * Find models matching given high flotation tire
     *
     * @param  float $tire_diameter Tire diameter, in (e.g. &#x60;31&#x60;) (required)
     * @param  float $tire_section_width Tire section width, in (e.g. &#x60;10.5&#x60;) (required)
     * @param  float $rim_diameter_hf Rim diameter, in (e.g. &#x60;15&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WsApiClient\Model\MakeWithModels[]
     */
    public function searchByHfTireList($tire_diameter, $tire_section_width, $rim_diameter_hf, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        list($response) = $this->searchByHfTireListWithHttpInfo($tire_diameter, $tire_section_width, $rim_diameter_hf, $lang, $brands, $brands_exclude, $countries, $countries_exclude);
        return $response;
    }

    /**
     * Operation searchByHfTireListWithHttpInfo
     *
     * Find models matching given high flotation tire
     *
     * @param  float $tire_diameter Tire diameter, in (e.g. &#x60;31&#x60;) (required)
     * @param  float $tire_section_width Tire section width, in (e.g. &#x60;10.5&#x60;) (required)
     * @param  float $rim_diameter_hf Rim diameter, in (e.g. &#x60;15&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WsApiClient\Model\MakeWithModels[], HTTP status code, HTTP response headers (array of strings)
     */
    public function searchByHfTireListWithHttpInfo($tire_diameter, $tire_section_width, $rim_diameter_hf, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\MakeWithModels[]';
        $request = $this->searchByHfTireListRequest($tire_diameter, $tire_section_width, $rim_diameter_hf, $lang, $brands, $brands_exclude, $countries, $countries_exclude);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WsApiClient\Model\MakeWithModels[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchByHfTireListAsync
     *
     * Find models matching given high flotation tire
     *
     * @param  float $tire_diameter Tire diameter, in (e.g. &#x60;31&#x60;) (required)
     * @param  float $tire_section_width Tire section width, in (e.g. &#x60;10.5&#x60;) (required)
     * @param  float $rim_diameter_hf Rim diameter, in (e.g. &#x60;15&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByHfTireListAsync($tire_diameter, $tire_section_width, $rim_diameter_hf, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        return $this->searchByHfTireListAsyncWithHttpInfo($tire_diameter, $tire_section_width, $rim_diameter_hf, $lang, $brands, $brands_exclude, $countries, $countries_exclude)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchByHfTireListAsyncWithHttpInfo
     *
     * Find models matching given high flotation tire
     *
     * @param  float $tire_diameter Tire diameter, in (e.g. &#x60;31&#x60;) (required)
     * @param  float $tire_section_width Tire section width, in (e.g. &#x60;10.5&#x60;) (required)
     * @param  float $rim_diameter_hf Rim diameter, in (e.g. &#x60;15&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByHfTireListAsyncWithHttpInfo($tire_diameter, $tire_section_width, $rim_diameter_hf, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\MakeWithModels[]';
        $request = $this->searchByHfTireListRequest($tire_diameter, $tire_section_width, $rim_diameter_hf, $lang, $brands, $brands_exclude, $countries, $countries_exclude);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchByHfTireList'
     *
     * @param  float $tire_diameter Tire diameter, in (e.g. &#x60;31&#x60;) (required)
     * @param  float $tire_section_width Tire section width, in (e.g. &#x60;10.5&#x60;) (required)
     * @param  float $rim_diameter_hf Rim diameter, in (e.g. &#x60;15&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchByHfTireListRequest($tire_diameter, $tire_section_width, $rim_diameter_hf, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        // verify the required parameter 'tire_diameter' is set
        if ($tire_diameter === null || (is_array($tire_diameter) && count($tire_diameter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tire_diameter when calling searchByHfTireList'
            );
        }
        // verify the required parameter 'tire_section_width' is set
        if ($tire_section_width === null || (is_array($tire_section_width) && count($tire_section_width) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tire_section_width when calling searchByHfTireList'
            );
        }
        // verify the required parameter 'rim_diameter_hf' is set
        if ($rim_diameter_hf === null || (is_array($rim_diameter_hf) && count($rim_diameter_hf) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rim_diameter_hf when calling searchByHfTireList'
            );
        }

        $resourcePath = '/search/by_hf_tire/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($tire_diameter !== null) {
            $queryParams['tire_diameter'] = ObjectSerializer::toQueryValue($tire_diameter);
        }
        // query params
        if ($tire_section_width !== null) {
            $queryParams['tire_section_width'] = ObjectSerializer::toQueryValue($tire_section_width);
        }
        // query params
        if ($rim_diameter_hf !== null) {
            $queryParams['rim_diameter_hf'] = ObjectSerializer::toQueryValue($rim_diameter_hf);
        }
        // query params
        if ($lang !== null) {
            $queryParams['lang'] = ObjectSerializer::toQueryValue($lang);
        }
        // query params
        if ($brands !== null) {
            $queryParams['brands'] = ObjectSerializer::toQueryValue($brands);
        }
        // query params
        if ($brands_exclude !== null) {
            $queryParams['brands_exclude'] = ObjectSerializer::toQueryValue($brands_exclude);
        }
        // query params
        if ($countries !== null) {
            $queryParams['countries'] = ObjectSerializer::toQueryValue($countries);
        }
        // query params
        if ($countries_exclude !== null) {
            $queryParams['countries_exclude'] = ObjectSerializer::toQueryValue($countries_exclude);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchByModelList
     *
     * Find OE and option fitments by model/year/trim
     *
     * @param  string $make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;) (required)
     * @param  int $year You can use _**&#x60;GET /years/&#x60;**_ to get possible years (e.g. &#x60;2015&#x60;) (required)
     * @param  string $trim Use *&#x60;slug&#x60;* from _**&#x60;GET /trims/&#x60;**_ methods here. (e.g. &#x60;2.0+GG2W&#x60;) (optional)
     * @param  bool $only_oem Show only original equipment wheels (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WsApiClient\Model\Vehicle[]
     */
    public function searchByModelList($make, $model, $year, $trim = null, $only_oem = null, $lang = null)
    {
        list($response) = $this->searchByModelListWithHttpInfo($make, $model, $year, $trim, $only_oem, $lang);
        return $response;
    }

    /**
     * Operation searchByModelListWithHttpInfo
     *
     * Find OE and option fitments by model/year/trim
     *
     * @param  string $make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;) (required)
     * @param  int $year You can use _**&#x60;GET /years/&#x60;**_ to get possible years (e.g. &#x60;2015&#x60;) (required)
     * @param  string $trim Use *&#x60;slug&#x60;* from _**&#x60;GET /trims/&#x60;**_ methods here. (e.g. &#x60;2.0+GG2W&#x60;) (optional)
     * @param  bool $only_oem Show only original equipment wheels (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WsApiClient\Model\Vehicle[], HTTP status code, HTTP response headers (array of strings)
     */
    public function searchByModelListWithHttpInfo($make, $model, $year, $trim = null, $only_oem = null, $lang = null)
    {
        $returnType = '\WsApiClient\Model\Vehicle[]';
        $request = $this->searchByModelListRequest($make, $model, $year, $trim, $only_oem, $lang);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WsApiClient\Model\Vehicle[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchByModelListAsync
     *
     * Find OE and option fitments by model/year/trim
     *
     * @param  string $make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;) (required)
     * @param  int $year You can use _**&#x60;GET /years/&#x60;**_ to get possible years (e.g. &#x60;2015&#x60;) (required)
     * @param  string $trim Use *&#x60;slug&#x60;* from _**&#x60;GET /trims/&#x60;**_ methods here. (e.g. &#x60;2.0+GG2W&#x60;) (optional)
     * @param  bool $only_oem Show only original equipment wheels (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByModelListAsync($make, $model, $year, $trim = null, $only_oem = null, $lang = null)
    {
        return $this->searchByModelListAsyncWithHttpInfo($make, $model, $year, $trim, $only_oem, $lang)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchByModelListAsyncWithHttpInfo
     *
     * Find OE and option fitments by model/year/trim
     *
     * @param  string $make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;) (required)
     * @param  int $year You can use _**&#x60;GET /years/&#x60;**_ to get possible years (e.g. &#x60;2015&#x60;) (required)
     * @param  string $trim Use *&#x60;slug&#x60;* from _**&#x60;GET /trims/&#x60;**_ methods here. (e.g. &#x60;2.0+GG2W&#x60;) (optional)
     * @param  bool $only_oem Show only original equipment wheels (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByModelListAsyncWithHttpInfo($make, $model, $year, $trim = null, $only_oem = null, $lang = null)
    {
        $returnType = '\WsApiClient\Model\Vehicle[]';
        $request = $this->searchByModelListRequest($make, $model, $year, $trim, $only_oem, $lang);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchByModelList'
     *
     * @param  string $make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;) (required)
     * @param  int $year You can use _**&#x60;GET /years/&#x60;**_ to get possible years (e.g. &#x60;2015&#x60;) (required)
     * @param  string $trim Use *&#x60;slug&#x60;* from _**&#x60;GET /trims/&#x60;**_ methods here. (e.g. &#x60;2.0+GG2W&#x60;) (optional)
     * @param  bool $only_oem Show only original equipment wheels (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchByModelListRequest($make, $model, $year, $trim = null, $only_oem = null, $lang = null)
    {
        // verify the required parameter 'make' is set
        if ($make === null || (is_array($make) && count($make) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $make when calling searchByModelList'
            );
        }
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling searchByModelList'
            );
        }
        // verify the required parameter 'year' is set
        if ($year === null || (is_array($year) && count($year) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $year when calling searchByModelList'
            );
        }

        $resourcePath = '/search/by_model/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($make !== null) {
            $queryParams['make'] = ObjectSerializer::toQueryValue($make);
        }
        // query params
        if ($model !== null) {
            $queryParams['model'] = ObjectSerializer::toQueryValue($model);
        }
        // query params
        if ($year !== null) {
            $queryParams['year'] = ObjectSerializer::toQueryValue($year);
        }
        // query params
        if ($trim !== null) {
            $queryParams['trim'] = ObjectSerializer::toQueryValue($trim);
        }
        // query params
        if ($only_oem !== null) {
            $queryParams['only_oem'] = ObjectSerializer::toQueryValue($only_oem);
        }
        // query params
        if ($lang !== null) {
            $queryParams['lang'] = ObjectSerializer::toQueryValue($lang);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchByRimList
     *
     * Find models matching given rim parameters
     *
     * @param  string $bolt_pattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  float $rim_width Rim width, in (e.g. &#x60;7&#x60;) (required)
     * @param  float $offset Rim offset, mm (e.g. &#x60;40&#x60;) (optional)
     * @param  float $offset_min Lower bound for rim offset, mm (e.g. &#x60;35&#x60;) (optional)
     * @param  float $offset_max Upper bound for rim offset, mm (e.g. &#x60;45&#x60;) (optional)
     * @param  float $cb Centre bore value, mm (e.g. &#x60;60&#x60;) (optional)
     * @param  float $cb_min Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;) (optional)
     * @param  float $cb_max Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WsApiClient\Model\MakeWithModels[]
     */
    public function searchByRimList($bolt_pattern, $rim_diameter, $rim_width, $offset = null, $offset_min = null, $offset_max = null, $cb = null, $cb_min = null, $cb_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        list($response) = $this->searchByRimListWithHttpInfo($bolt_pattern, $rim_diameter, $rim_width, $offset, $offset_min, $offset_max, $cb, $cb_min, $cb_max, $lang, $brands, $brands_exclude, $countries, $countries_exclude);
        return $response;
    }

    /**
     * Operation searchByRimListWithHttpInfo
     *
     * Find models matching given rim parameters
     *
     * @param  string $bolt_pattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  float $rim_width Rim width, in (e.g. &#x60;7&#x60;) (required)
     * @param  float $offset Rim offset, mm (e.g. &#x60;40&#x60;) (optional)
     * @param  float $offset_min Lower bound for rim offset, mm (e.g. &#x60;35&#x60;) (optional)
     * @param  float $offset_max Upper bound for rim offset, mm (e.g. &#x60;45&#x60;) (optional)
     * @param  float $cb Centre bore value, mm (e.g. &#x60;60&#x60;) (optional)
     * @param  float $cb_min Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;) (optional)
     * @param  float $cb_max Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WsApiClient\Model\MakeWithModels[], HTTP status code, HTTP response headers (array of strings)
     */
    public function searchByRimListWithHttpInfo($bolt_pattern, $rim_diameter, $rim_width, $offset = null, $offset_min = null, $offset_max = null, $cb = null, $cb_min = null, $cb_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\MakeWithModels[]';
        $request = $this->searchByRimListRequest($bolt_pattern, $rim_diameter, $rim_width, $offset, $offset_min, $offset_max, $cb, $cb_min, $cb_max, $lang, $brands, $brands_exclude, $countries, $countries_exclude);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WsApiClient\Model\MakeWithModels[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchByRimListAsync
     *
     * Find models matching given rim parameters
     *
     * @param  string $bolt_pattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  float $rim_width Rim width, in (e.g. &#x60;7&#x60;) (required)
     * @param  float $offset Rim offset, mm (e.g. &#x60;40&#x60;) (optional)
     * @param  float $offset_min Lower bound for rim offset, mm (e.g. &#x60;35&#x60;) (optional)
     * @param  float $offset_max Upper bound for rim offset, mm (e.g. &#x60;45&#x60;) (optional)
     * @param  float $cb Centre bore value, mm (e.g. &#x60;60&#x60;) (optional)
     * @param  float $cb_min Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;) (optional)
     * @param  float $cb_max Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByRimListAsync($bolt_pattern, $rim_diameter, $rim_width, $offset = null, $offset_min = null, $offset_max = null, $cb = null, $cb_min = null, $cb_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        return $this->searchByRimListAsyncWithHttpInfo($bolt_pattern, $rim_diameter, $rim_width, $offset, $offset_min, $offset_max, $cb, $cb_min, $cb_max, $lang, $brands, $brands_exclude, $countries, $countries_exclude)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchByRimListAsyncWithHttpInfo
     *
     * Find models matching given rim parameters
     *
     * @param  string $bolt_pattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  float $rim_width Rim width, in (e.g. &#x60;7&#x60;) (required)
     * @param  float $offset Rim offset, mm (e.g. &#x60;40&#x60;) (optional)
     * @param  float $offset_min Lower bound for rim offset, mm (e.g. &#x60;35&#x60;) (optional)
     * @param  float $offset_max Upper bound for rim offset, mm (e.g. &#x60;45&#x60;) (optional)
     * @param  float $cb Centre bore value, mm (e.g. &#x60;60&#x60;) (optional)
     * @param  float $cb_min Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;) (optional)
     * @param  float $cb_max Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByRimListAsyncWithHttpInfo($bolt_pattern, $rim_diameter, $rim_width, $offset = null, $offset_min = null, $offset_max = null, $cb = null, $cb_min = null, $cb_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\MakeWithModels[]';
        $request = $this->searchByRimListRequest($bolt_pattern, $rim_diameter, $rim_width, $offset, $offset_min, $offset_max, $cb, $cb_min, $cb_max, $lang, $brands, $brands_exclude, $countries, $countries_exclude);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchByRimList'
     *
     * @param  string $bolt_pattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  float $rim_width Rim width, in (e.g. &#x60;7&#x60;) (required)
     * @param  float $offset Rim offset, mm (e.g. &#x60;40&#x60;) (optional)
     * @param  float $offset_min Lower bound for rim offset, mm (e.g. &#x60;35&#x60;) (optional)
     * @param  float $offset_max Upper bound for rim offset, mm (e.g. &#x60;45&#x60;) (optional)
     * @param  float $cb Centre bore value, mm (e.g. &#x60;60&#x60;) (optional)
     * @param  float $cb_min Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;) (optional)
     * @param  float $cb_max Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchByRimListRequest($bolt_pattern, $rim_diameter, $rim_width, $offset = null, $offset_min = null, $offset_max = null, $cb = null, $cb_min = null, $cb_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        // verify the required parameter 'bolt_pattern' is set
        if ($bolt_pattern === null || (is_array($bolt_pattern) && count($bolt_pattern) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bolt_pattern when calling searchByRimList'
            );
        }
        // verify the required parameter 'rim_diameter' is set
        if ($rim_diameter === null || (is_array($rim_diameter) && count($rim_diameter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rim_diameter when calling searchByRimList'
            );
        }
        // verify the required parameter 'rim_width' is set
        if ($rim_width === null || (is_array($rim_width) && count($rim_width) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rim_width when calling searchByRimList'
            );
        }

        $resourcePath = '/search/by_rim/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($bolt_pattern !== null) {
            $queryParams['bolt_pattern'] = ObjectSerializer::toQueryValue($bolt_pattern);
        }
        // query params
        if ($rim_diameter !== null) {
            $queryParams['rim_diameter'] = ObjectSerializer::toQueryValue($rim_diameter);
        }
        // query params
        if ($rim_width !== null) {
            $queryParams['rim_width'] = ObjectSerializer::toQueryValue($rim_width);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }
        // query params
        if ($offset_min !== null) {
            $queryParams['offset_min'] = ObjectSerializer::toQueryValue($offset_min);
        }
        // query params
        if ($offset_max !== null) {
            $queryParams['offset_max'] = ObjectSerializer::toQueryValue($offset_max);
        }
        // query params
        if ($cb !== null) {
            $queryParams['cb'] = ObjectSerializer::toQueryValue($cb);
        }
        // query params
        if ($cb_min !== null) {
            $queryParams['cb_min'] = ObjectSerializer::toQueryValue($cb_min);
        }
        // query params
        if ($cb_max !== null) {
            $queryParams['cb_max'] = ObjectSerializer::toQueryValue($cb_max);
        }
        // query params
        if ($lang !== null) {
            $queryParams['lang'] = ObjectSerializer::toQueryValue($lang);
        }
        // query params
        if ($brands !== null) {
            $queryParams['brands'] = ObjectSerializer::toQueryValue($brands);
        }
        // query params
        if ($brands_exclude !== null) {
            $queryParams['brands_exclude'] = ObjectSerializer::toQueryValue($brands_exclude);
        }
        // query params
        if ($countries !== null) {
            $queryParams['countries'] = ObjectSerializer::toQueryValue($countries);
        }
        // query params
        if ($countries_exclude !== null) {
            $queryParams['countries_exclude'] = ObjectSerializer::toQueryValue($countries_exclude);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchByTireList
     *
     * Find models matching given tire parameters
     *
     * @param  float $tire_width Tire width, mm (e.g. &#x60;195&#x60;) (required)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WsApiClient\Model\MakeWithModels[]
     */
    public function searchByTireList($tire_width, $aspect_ratio, $rim_diameter, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        list($response) = $this->searchByTireListWithHttpInfo($tire_width, $aspect_ratio, $rim_diameter, $lang, $brands, $brands_exclude, $countries, $countries_exclude);
        return $response;
    }

    /**
     * Operation searchByTireListWithHttpInfo
     *
     * Find models matching given tire parameters
     *
     * @param  float $tire_width Tire width, mm (e.g. &#x60;195&#x60;) (required)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WsApiClient\Model\MakeWithModels[], HTTP status code, HTTP response headers (array of strings)
     */
    public function searchByTireListWithHttpInfo($tire_width, $aspect_ratio, $rim_diameter, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\MakeWithModels[]';
        $request = $this->searchByTireListRequest($tire_width, $aspect_ratio, $rim_diameter, $lang, $brands, $brands_exclude, $countries, $countries_exclude);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WsApiClient\Model\MakeWithModels[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchByTireListAsync
     *
     * Find models matching given tire parameters
     *
     * @param  float $tire_width Tire width, mm (e.g. &#x60;195&#x60;) (required)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByTireListAsync($tire_width, $aspect_ratio, $rim_diameter, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        return $this->searchByTireListAsyncWithHttpInfo($tire_width, $aspect_ratio, $rim_diameter, $lang, $brands, $brands_exclude, $countries, $countries_exclude)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchByTireListAsyncWithHttpInfo
     *
     * Find models matching given tire parameters
     *
     * @param  float $tire_width Tire width, mm (e.g. &#x60;195&#x60;) (required)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByTireListAsyncWithHttpInfo($tire_width, $aspect_ratio, $rim_diameter, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\MakeWithModels[]';
        $request = $this->searchByTireListRequest($tire_width, $aspect_ratio, $rim_diameter, $lang, $brands, $brands_exclude, $countries, $countries_exclude);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchByTireList'
     *
     * @param  float $tire_width Tire width, mm (e.g. &#x60;195&#x60;) (required)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (required)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchByTireListRequest($tire_width, $aspect_ratio, $rim_diameter, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        // verify the required parameter 'tire_width' is set
        if ($tire_width === null || (is_array($tire_width) && count($tire_width) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tire_width when calling searchByTireList'
            );
        }
        // verify the required parameter 'aspect_ratio' is set
        if ($aspect_ratio === null || (is_array($aspect_ratio) && count($aspect_ratio) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $aspect_ratio when calling searchByTireList'
            );
        }
        // verify the required parameter 'rim_diameter' is set
        if ($rim_diameter === null || (is_array($rim_diameter) && count($rim_diameter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rim_diameter when calling searchByTireList'
            );
        }

        $resourcePath = '/search/by_tire/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($tire_width !== null) {
            $queryParams['tire_width'] = ObjectSerializer::toQueryValue($tire_width);
        }
        // query params
        if ($aspect_ratio !== null) {
            $queryParams['aspect_ratio'] = ObjectSerializer::toQueryValue($aspect_ratio);
        }
        // query params
        if ($rim_diameter !== null) {
            $queryParams['rim_diameter'] = ObjectSerializer::toQueryValue($rim_diameter);
        }
        // query params
        if ($lang !== null) {
            $queryParams['lang'] = ObjectSerializer::toQueryValue($lang);
        }
        // query params
        if ($brands !== null) {
            $queryParams['brands'] = ObjectSerializer::toQueryValue($brands);
        }
        // query params
        if ($brands_exclude !== null) {
            $queryParams['brands_exclude'] = ObjectSerializer::toQueryValue($brands_exclude);
        }
        // query params
        if ($countries !== null) {
            $queryParams['countries'] = ObjectSerializer::toQueryValue($countries);
        }
        // query params
        if ($countries_exclude !== null) {
            $queryParams['countries_exclude'] = ObjectSerializer::toQueryValue($countries_exclude);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
