<?php
/**
 * TiresApi
 * PHP version 5
 *
 * @category Class
 * @package  WsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Fitment API
 *
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace WsApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use WsApiClient\ApiException;
use WsApiClient\Configuration;
use WsApiClient\HeaderSelector;
use WsApiClient\ObjectSerializer;

/**
 * TiresApi Class Doc Comment
 *
 * @category Class
 * @package  WsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TiresApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation tiresList
     *
     * Returns a list of tires
     *
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WsApiClient\Model\Tire[]
     */
    public function tiresList($width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        list($response) = $this->tiresListWithHttpInfo($width, $width_min, $width_max, $aspect_ratio, $aspect_ratio_min, $aspect_ratio_max, $rim_diameter, $rim_diameter_min, $rim_diameter_max, $brands, $brands_exclude, $countries, $countries_exclude);
        return $response;
    }

    /**
     * Operation tiresListWithHttpInfo
     *
     * Returns a list of tires
     *
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WsApiClient\Model\Tire[], HTTP status code, HTTP response headers (array of strings)
     */
    public function tiresListWithHttpInfo($width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\Tire[]';
        $request = $this->tiresListRequest($width, $width_min, $width_max, $aspect_ratio, $aspect_ratio_min, $aspect_ratio_max, $rim_diameter, $rim_diameter_min, $rim_diameter_max, $brands, $brands_exclude, $countries, $countries_exclude);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WsApiClient\Model\Tire[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tiresListAsync
     *
     * Returns a list of tires
     *
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tiresListAsync($width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        return $this->tiresListAsyncWithHttpInfo($width, $width_min, $width_max, $aspect_ratio, $aspect_ratio_min, $aspect_ratio_max, $rim_diameter, $rim_diameter_min, $rim_diameter_max, $brands, $brands_exclude, $countries, $countries_exclude)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tiresListAsyncWithHttpInfo
     *
     * Returns a list of tires
     *
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tiresListAsyncWithHttpInfo($width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\Tire[]';
        $request = $this->tiresListRequest($width, $width_min, $width_max, $aspect_ratio, $aspect_ratio_min, $aspect_ratio_max, $rim_diameter, $rim_diameter_min, $rim_diameter_max, $brands, $brands_exclude, $countries, $countries_exclude);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tiresList'
     *
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function tiresListRequest($width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {

        $resourcePath = '/tires/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($width !== null) {
            $queryParams['width'] = ObjectSerializer::toQueryValue($width);
        }
        // query params
        if ($width_min !== null) {
            $queryParams['width_min'] = ObjectSerializer::toQueryValue($width_min);
        }
        // query params
        if ($width_max !== null) {
            $queryParams['width_max'] = ObjectSerializer::toQueryValue($width_max);
        }
        // query params
        if ($aspect_ratio !== null) {
            $queryParams['aspect_ratio'] = ObjectSerializer::toQueryValue($aspect_ratio);
        }
        // query params
        if ($aspect_ratio_min !== null) {
            $queryParams['aspect_ratio_min'] = ObjectSerializer::toQueryValue($aspect_ratio_min);
        }
        // query params
        if ($aspect_ratio_max !== null) {
            $queryParams['aspect_ratio_max'] = ObjectSerializer::toQueryValue($aspect_ratio_max);
        }
        // query params
        if ($rim_diameter !== null) {
            $queryParams['rim_diameter'] = ObjectSerializer::toQueryValue($rim_diameter);
        }
        // query params
        if ($rim_diameter_min !== null) {
            $queryParams['rim_diameter_min'] = ObjectSerializer::toQueryValue($rim_diameter_min);
        }
        // query params
        if ($rim_diameter_max !== null) {
            $queryParams['rim_diameter_max'] = ObjectSerializer::toQueryValue($rim_diameter_max);
        }
        // query params
        if ($brands !== null) {
            $queryParams['brands'] = ObjectSerializer::toQueryValue($brands);
        }
        // query params
        if ($brands_exclude !== null) {
            $queryParams['brands_exclude'] = ObjectSerializer::toQueryValue($brands_exclude);
        }
        // query params
        if ($countries !== null) {
            $queryParams['countries'] = ObjectSerializer::toQueryValue($countries);
        }
        // query params
        if ($countries_exclude !== null) {
            $queryParams['countries_exclude'] = ObjectSerializer::toQueryValue($countries_exclude);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation tiresRead
     *
     * Model modifications matching given tire
     *
     * @param  string $tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;) (required)
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WsApiClient\Model\MakeWithModels[]
     */
    public function tiresRead($tire, $width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        list($response) = $this->tiresReadWithHttpInfo($tire, $width, $width_min, $width_max, $aspect_ratio, $aspect_ratio_min, $aspect_ratio_max, $rim_diameter, $rim_diameter_min, $rim_diameter_max, $lang, $brands, $brands_exclude, $countries, $countries_exclude);
        return $response;
    }

    /**
     * Operation tiresReadWithHttpInfo
     *
     * Model modifications matching given tire
     *
     * @param  string $tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;) (required)
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \WsApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WsApiClient\Model\MakeWithModels[], HTTP status code, HTTP response headers (array of strings)
     */
    public function tiresReadWithHttpInfo($tire, $width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\MakeWithModels[]';
        $request = $this->tiresReadRequest($tire, $width, $width_min, $width_max, $aspect_ratio, $aspect_ratio_min, $aspect_ratio_max, $rim_diameter, $rim_diameter_min, $rim_diameter_max, $lang, $brands, $brands_exclude, $countries, $countries_exclude);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WsApiClient\Model\MakeWithModels[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tiresReadAsync
     *
     * Model modifications matching given tire
     *
     * @param  string $tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;) (required)
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tiresReadAsync($tire, $width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        return $this->tiresReadAsyncWithHttpInfo($tire, $width, $width_min, $width_max, $aspect_ratio, $aspect_ratio_min, $aspect_ratio_max, $rim_diameter, $rim_diameter_min, $rim_diameter_max, $lang, $brands, $brands_exclude, $countries, $countries_exclude)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tiresReadAsyncWithHttpInfo
     *
     * Model modifications matching given tire
     *
     * @param  string $tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;) (required)
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tiresReadAsyncWithHttpInfo($tire, $width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        $returnType = '\WsApiClient\Model\MakeWithModels[]';
        $request = $this->tiresReadRequest($tire, $width, $width_min, $width_max, $aspect_ratio, $aspect_ratio_min, $aspect_ratio_max, $rim_diameter, $rim_diameter_min, $rim_diameter_max, $lang, $brands, $brands_exclude, $countries, $countries_exclude);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tiresRead'
     *
     * @param  string $tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;) (required)
     * @param  float $width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param  float $width_min Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param  float $width_max Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param  float $aspect_ratio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param  float $aspect_ratio_min Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param  float $aspect_ratio_max Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param  float $rim_diameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param  float $rim_diameter_min Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param  float $rim_diameter_max Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param  string $lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param  string $brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param  string $brands_exclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param  string $countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param  string $countries_exclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function tiresReadRequest($tire, $width = null, $width_min = null, $width_max = null, $aspect_ratio = null, $aspect_ratio_min = null, $aspect_ratio_max = null, $rim_diameter = null, $rim_diameter_min = null, $rim_diameter_max = null, $lang = null, $brands = null, $brands_exclude = null, $countries = null, $countries_exclude = null)
    {
        // verify the required parameter 'tire' is set
        if ($tire === null || (is_array($tire) && count($tire) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tire when calling tiresRead'
            );
        }

        $resourcePath = '/tires/{tire}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($width !== null) {
            $queryParams['width'] = ObjectSerializer::toQueryValue($width);
        }
        // query params
        if ($width_min !== null) {
            $queryParams['width_min'] = ObjectSerializer::toQueryValue($width_min);
        }
        // query params
        if ($width_max !== null) {
            $queryParams['width_max'] = ObjectSerializer::toQueryValue($width_max);
        }
        // query params
        if ($aspect_ratio !== null) {
            $queryParams['aspect_ratio'] = ObjectSerializer::toQueryValue($aspect_ratio);
        }
        // query params
        if ($aspect_ratio_min !== null) {
            $queryParams['aspect_ratio_min'] = ObjectSerializer::toQueryValue($aspect_ratio_min);
        }
        // query params
        if ($aspect_ratio_max !== null) {
            $queryParams['aspect_ratio_max'] = ObjectSerializer::toQueryValue($aspect_ratio_max);
        }
        // query params
        if ($rim_diameter !== null) {
            $queryParams['rim_diameter'] = ObjectSerializer::toQueryValue($rim_diameter);
        }
        // query params
        if ($rim_diameter_min !== null) {
            $queryParams['rim_diameter_min'] = ObjectSerializer::toQueryValue($rim_diameter_min);
        }
        // query params
        if ($rim_diameter_max !== null) {
            $queryParams['rim_diameter_max'] = ObjectSerializer::toQueryValue($rim_diameter_max);
        }
        // query params
        if ($lang !== null) {
            $queryParams['lang'] = ObjectSerializer::toQueryValue($lang);
        }
        // query params
        if ($brands !== null) {
            $queryParams['brands'] = ObjectSerializer::toQueryValue($brands);
        }
        // query params
        if ($brands_exclude !== null) {
            $queryParams['brands_exclude'] = ObjectSerializer::toQueryValue($brands_exclude);
        }
        // query params
        if ($countries !== null) {
            $queryParams['countries'] = ObjectSerializer::toQueryValue($countries);
        }
        // query params
        if ($countries_exclude !== null) {
            $queryParams['countries_exclude'] = ObjectSerializer::toQueryValue($countries_exclude);
        }

        // path params
        if ($tire !== null) {
            $resourcePath = str_replace(
                '{' . 'tire' . '}',
                ObjectSerializer::toPathValue($tire),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
