<?php
/**
 * ModelWithTiresTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  WsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Fitment API
 *
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace WsApiClient;

/**
 * ModelWithTiresTest Class Doc Comment
 *
 * @category    Class
 * @description ModelWithTires
 * @package     WsApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelWithTiresTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelWithTires"
     */
    public function testModelWithTires()
    {
    }

    /**
     * Test attribute "make"
     */
    public function testPropertyMake()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "years"
     */
    public function testPropertyYears()
    {
    }

    /**
     * Test attribute "generations"
     */
    public function testPropertyGenerations()
    {
    }

    /**
     * Test attribute "tires"
     */
    public function testPropertyTires()
    {
    }

    /**
     * Test attribute "rims"
     */
    public function testPropertyRims()
    {
    }
}
