<?php
/**
 * ModelWithTires
 *
 * PHP version 5
 *
 * @category Class
 * @package  WsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Fitment API
 *
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace WsApiClient\Model;

use \ArrayAccess;
use \WsApiClient\ObjectSerializer;

/**
 * ModelWithTires Class Doc Comment
 *
 * @category Class
 * @package  WsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ModelWithTires implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ModelWithTires';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'make' => '\WsApiClient\Model\MakeModel',
        'model' => '\WsApiClient\Model\Model',
        'year' => 'int',
        'years' => 'int[]',
        'generations' => '\WsApiClient\Model\Generation[]',
        'tires' => '\WsApiClient\Model\TiresAggregation',
        'rims' => 'map[string,\WsApiClient\Model\RimAgregation]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'make' => null,
        'model' => null,
        'year' => null,
        'years' => null,
        'generations' => null,
        'tires' => null,
        'rims' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'make' => 'make',
        'model' => 'model',
        'year' => 'year',
        'years' => 'years',
        'generations' => 'generations',
        'tires' => 'tires',
        'rims' => 'rims'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'make' => 'setMake',
        'model' => 'setModel',
        'year' => 'setYear',
        'years' => 'setYears',
        'generations' => 'setGenerations',
        'tires' => 'setTires',
        'rims' => 'setRims'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'make' => 'getMake',
        'model' => 'getModel',
        'year' => 'getYear',
        'years' => 'getYears',
        'generations' => 'getGenerations',
        'tires' => 'getTires',
        'rims' => 'getRims'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['make'] = isset($data['make']) ? $data['make'] : null;
        $this->container['model'] = isset($data['model']) ? $data['model'] : null;
        $this->container['year'] = isset($data['year']) ? $data['year'] : null;
        $this->container['years'] = isset($data['years']) ? $data['years'] : null;
        $this->container['generations'] = isset($data['generations']) ? $data['generations'] : null;
        $this->container['tires'] = isset($data['tires']) ? $data['tires'] : null;
        $this->container['rims'] = isset($data['rims']) ? $data['rims'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['make'] === null) {
            $invalidProperties[] = "'make' can't be null";
        }
        if ($this->container['model'] === null) {
            $invalidProperties[] = "'model' can't be null";
        }
        if ($this->container['year'] === null) {
            $invalidProperties[] = "'year' can't be null";
        }
        if ($this->container['generations'] === null) {
            $invalidProperties[] = "'generations' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['make'] === null) {
            return false;
        }
        if ($this->container['model'] === null) {
            return false;
        }
        if ($this->container['year'] === null) {
            return false;
        }
        if ($this->container['generations'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets make
     *
     * @return \WsApiClient\Model\MakeModel
     */
    public function getMake()
    {
        return $this->container['make'];
    }

    /**
     * Sets make
     *
     * @param \WsApiClient\Model\MakeModel $make make
     *
     * @return $this
     */
    public function setMake($make)
    {
        $this->container['make'] = $make;

        return $this;
    }

    /**
     * Gets model
     *
     * @return \WsApiClient\Model\Model
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param \WsApiClient\Model\Model $model model
     *
     * @return $this
     */
    public function setModel($model)
    {
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets year
     *
     * @return int
     */
    public function getYear()
    {
        return $this->container['year'];
    }

    /**
     * Sets year
     *
     * @param int $year Selected year (e.g. `2015`, can be __*`null`*__)
     *
     * @return $this
     */
    public function setYear($year)
    {
        $this->container['year'] = $year;

        return $this;
    }

    /**
     * Gets years
     *
     * @return int[]
     */
    public function getYears()
    {
        return $this->container['years'];
    }

    /**
     * Sets years
     *
     * @param int[] $years Model production years
     *
     * @return $this
     */
    public function setYears($years)
    {
        $this->container['years'] = $years;

        return $this;
    }

    /**
     * Gets generations
     *
     * @return \WsApiClient\Model\Generation[]
     */
    public function getGenerations()
    {
        return $this->container['generations'];
    }

    /**
     * Sets generations
     *
     * @param \WsApiClient\Model\Generation[] $generations generations
     *
     * @return $this
     */
    public function setGenerations($generations)
    {
        $this->container['generations'] = $generations;

        return $this;
    }

    /**
     * Gets tires
     *
     * @return \WsApiClient\Model\TiresAggregation
     */
    public function getTires()
    {
        return $this->container['tires'];
    }

    /**
     * Sets tires
     *
     * @param \WsApiClient\Model\TiresAggregation $tires tires
     *
     * @return $this
     */
    public function setTires($tires)
    {
        $this->container['tires'] = $tires;

        return $this;
    }

    /**
     * Gets rims
     *
     * @return map[string,\WsApiClient\Model\RimAgregation]
     */
    public function getRims()
    {
        return $this->container['rims'];
    }

    /**
     * Sets rims
     *
     * @param map[string,\WsApiClient\Model\RimAgregation] $rims Each key is bolt pattern, e.g. *`5x105`*
     *
     * @return $this
     */
    public function setRims($rims)
    {
        $this->container['rims'] = $rims;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


