<?php
/**
 * VehicleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  WsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Fitment API
 *
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace WsApiClient;

/**
 * VehicleTest Class Doc Comment
 *
 * @category    Class
 * @description Vehicle
 * @package     WsApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VehicleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Vehicle"
     */
    public function testVehicle()
    {
    }

    /**
     * Test attribute "market"
     */
    public function testPropertyMarket()
    {
    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {
    }

    /**
     * Test attribute "trim"
     */
    public function testPropertyTrim()
    {
    }

    /**
     * Test attribute "generation"
     */
    public function testPropertyGeneration()
    {
    }

    /**
     * Test attribute "stud_holes"
     */
    public function testPropertyStudHoles()
    {
    }

    /**
     * Test attribute "pcd"
     */
    public function testPropertyPcd()
    {
    }

    /**
     * Test attribute "centre_bore"
     */
    public function testPropertyCentreBore()
    {
    }

    /**
     * Test attribute "lock_type"
     */
    public function testPropertyLockType()
    {
    }

    /**
     * Test attribute "lock_text"
     */
    public function testPropertyLockText()
    {
    }

    /**
     * Test attribute "bolt_pattern"
     */
    public function testPropertyBoltPattern()
    {
    }

    /**
     * Test attribute "power"
     */
    public function testPropertyPower()
    {
    }

    /**
     * Test attribute "fuel"
     */
    public function testPropertyFuel()
    {
    }

    /**
     * Test attribute "wheels"
     */
    public function testPropertyWheels()
    {
    }
}
