<?php
/**
 * WheelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  WsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Fitment API
 *
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace WsApiClient;

/**
 * WheelTest Class Doc Comment
 *
 * @category    Class
 * @description Wheel
 * @package     WsApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WheelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Wheel"
     */
    public function testWheel()
    {
    }

    /**
     * Test attribute "tire_pressure"
     */
    public function testPropertyTirePressure()
    {
    }

    /**
     * Test attribute "rim"
     */
    public function testPropertyRim()
    {
    }

    /**
     * Test attribute "rim_diameter"
     */
    public function testPropertyRimDiameter()
    {
    }

    /**
     * Test attribute "rim_width"
     */
    public function testPropertyRimWidth()
    {
    }

    /**
     * Test attribute "rim_offset"
     */
    public function testPropertyRimOffset()
    {
    }

    /**
     * Test attribute "tire"
     */
    public function testPropertyTire()
    {
    }

    /**
     * Test attribute "tire_sizing_system"
     */
    public function testPropertyTireSizingSystem()
    {
    }

    /**
     * Test attribute "tire_construction"
     */
    public function testPropertyTireConstruction()
    {
    }

    /**
     * Test attribute "tire_width"
     */
    public function testPropertyTireWidth()
    {
    }

    /**
     * Test attribute "tire_aspect_ratio"
     */
    public function testPropertyTireAspectRatio()
    {
    }

    /**
     * Test attribute "tire_diameter"
     */
    public function testPropertyTireDiameter()
    {
    }

    /**
     * Test attribute "tire_section_width"
     */
    public function testPropertyTireSectionWidth()
    {
    }

    /**
     * Test attribute "tire_is_82series"
     */
    public function testPropertyTireIs82series()
    {
    }

    /**
     * Test attribute "load_index"
     */
    public function testPropertyLoadIndex()
    {
    }

    /**
     * Test attribute "speed_index"
     */
    public function testPropertySpeedIndex()
    {
    }
}
